### ISSUE TITLE
Actividad 2

### ISSUE THREAD

**Issue by edgarmauricio123** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-edgarmauricio123#1]
Edgar Mauricio Sarmiento Ruiz Grupo 1BS
Actividad 2 Infografía de proceso de construcción del conocimiento 

![PROCESO-DE-CONSTRUCCION-DEL-CONOCIMIENTO](https://user-images.githubusercontent.com/112227375/187592341-d17a9cdc-8bca-4e3e-9331-407b57cf8e92.png)

**Comment by YaelTrinidad** [comment]
ACTIVIDAD 2 INFOGRAFIA
DE 20% DE LA ACTIVIDAD OBTUVISTE 16.4 % DE ACUERDO A LA RUBRICA

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
