### ISSUE TITLE
ACTIVIDAD 3

### ISSUE THREAD

**Issue by edgarmauricio123** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-edgarmauricio123#3]
Edgar Mauricio Sarmiento Ruiz Grupo: 1BS
Actividad 3 trabajo que se volvió hacer

![CUADRO-COMPARATIVO-1](https://user-images.githubusercontent.com/112227375/189034603-8280c38f-ba2b-42e2-b590-ab4452102f15.png)

**Comment by YaelTrinidad** [comment]
ACTIVIDAD 3 CUADRO COMPARATIVO
DE 20% DE LA ACTIVIDAD OBTUVISTE 16.55 % DE ACUERDO A LA RUBRICA

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
